# 分析結果を集計するノートブック
- 一旦AUCだけで比較してみる
- output/ファイルから各手法の各データの結果をまとめる
- それらの平均をまとめる
- 分散分析とかグラフとかにして表示する

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
method = ['MTS', 'MTSBag', 'SMOTEMTSBag', 'LGBM', 'RUSB', 'SVM']
data = ['abalone', 'cancer', 'car', 'letter', 'wine', 'yeast']
e_index = ['AUC', 'accuracy', 'recall', 'Specificity', 'precision', 'gmeans', 'RS']
multi_columns = [
    np.array(
        [method[0]] * 2 + 
        [method[1]] * 2 + 
        [method[2]] * 2 + 
        [method[3]] * 2 +
        [method[4]] * 2 +
        [method[5]] * 2 
        ),
    np.array(["mean", "std"] * len(method))
]

In [15]:
for e in e_index:
    index_result_df = pd.DataFrame(
                index=data,
                columns=multi_columns,
                )
    for m in method:
        for d in data:     
            df = pd.read_csv(f'../data/output/{m}_{d}_result.csv', index_col=0)
            index_result_df.loc[d, m] = [df[e].mean(), df[e].std()]
    index_result_df.loc['whole_mean'] = index_result_df.mean(axis=0)
    print(e)
    display(index_result_df)
    index_result_df.to_csv(f'../data/output/{e}_score.csv')

AUC

                 MTS              MTSBag           SMOTEMTSBag            \
                mean       std      mean       std        mean       std
abalone     0.987171  0.002854  0.944392  0.043943    0.948068  0.010168
cancer      0.941452  0.044601  0.974452  0.007436    0.947739  0.007571
car         0.972992  0.009191  0.981707  0.010097    0.945115  0.005438
letter      0.918555  0.039022  0.913907  0.015599    0.950391  0.008753
wine        0.987432  0.010289  0.996923  0.006499    0.947626  0.009748
yeast       0.716786  0.097528  0.714422  0.097658    0.946119  0.010684
whole_mean  0.920731  0.033914  0.920967  0.030205     0.94751  0.008727

                LGBM                RUSB                 SVM
                mean       std      mean       std      mean       std
abalone     0.986441  0.004274  0.972084  0.023729  0.994257  0.001094
cancer      0.992864  0.004389  0.978632  0.010448  0.995518  0.003639
car         0.998552  0.001279  0.970475  0.005942  0.922685  0.028839
letter      0.999992  0.000011  0.990675  0.003313  0.983292  0.004769
wine        0.998161  0.003105  0.999271  0.001553  0.999015  0.003116
yeast        0.91689   0.02349  0.755767  0.090307  0.798036  0.144155
whole_mean   0.98215  0.006091  0.944484  0.022549  0.948801  0.030935

accuracy

                 MTS              MTSBag           SMOTEMTSBag            \
                mean       std      mean       std        mean       std
abalone     0.975359  0.004986  0.978828  0.002878    0.966725  0.012226
cancer      0.861429  0.178498     0.945  0.013063      0.9615  0.011696
car         0.954624  0.011239  0.962717  0.009961    0.963725  0.013658
letter      0.966425  0.010108  0.983725  0.002825      0.9673  0.008036
wine        0.955556  0.032605  0.988889  0.019422      0.9547  0.019257
yeast       0.946128  0.010528  0.945791  0.014325    0.963425  0.009458
whole_mean  0.943253  0.041328  0.967492  0.010412    0.962896  0.012389

                LGBM                RUSB                 SVM
                mean       std      mean       std      mean       std
abalone      0.98445  0.002875  0.966746  0.009909  0.981699  0.003949
cancer      0.958571  0.019284  0.950714  0.019474  0.970714  0.016306
car         0.991329  0.005098  0.945376  0.008112  0.960116  0.006062
letter      0.998775  0.000795   0.96805  0.005644    0.9914  0.001119
wine        0.966667  0.025526  0.988889  0.014344  0.986111  0.019642
yeast       0.960606   0.00953  0.857912  0.035978   0.96229  0.013165
whole_mean  0.976733  0.010518  0.946281  0.015577  0.975388  0.010041

recall

                 MTS              MTSBag           SMOTEMTSBag            \
                mean       std      mean       std        mean       std
abalone     0.864489  0.079437  0.828782  0.094719    0.829861  0.028208
cancer      0.895682  0.070463  0.966698  0.024807    0.818056  0.019312
car         0.933095   0.11409  0.915359  0.103246    0.819444  0.021715
letter      0.578205  0.073918  0.669604  0.050759    0.814583  0.020974
wine        0.918173  0.095862      0.99  0.031623    0.839583  0.014437
yeast       0.242955  0.121597  0.245328  0.195025       0.825  0.024888
whole_mean  0.738766  0.092561  0.769295  0.083363    0.824421  0.021589

                LGBM                RUSB                 SVM
                mean       std      mean       std      mean       std
abalone     0.525293  0.190426  0.808119  0.179485       0.0       0.0
cancer      0.940449  0.036771    0.9286  0.046167  0.954879  0.030464
car         0.888897   0.10924  0.764505  0.133396       0.0       0.0
letter      0.970367  0.020187  0.937506  0.024349   0.84905  0.023284
wine        0.937727  0.091313  0.990909  0.028748  0.975524  0.053689
yeast        0.15047   0.08672  0.539875  0.135139       0.0       0.0
whole_mean  0.735534   0.08911  0.828252  0.091214  0.463242  0.017906

Specificity

                 MTS              MTSBag           SMOTEMTSBag            \
                mean       std      mean       std        mean       std
abalone     0.977552  0.005468  0.981521  0.003552    0.971836  0.013192
cancer      0.840892  0.297744  0.933708   0.01815    0.966857  0.012242
car         0.955422  0.013726  0.965057  0.010286    0.969113  0.014619
letter      0.982797  0.008756  0.996618  0.001771    0.973003  0.008287
wine        0.966556  0.041178  0.986561  0.030457    0.958999  0.020182
yeast       0.966755   0.01166  0.973053  0.011402    0.968594  0.010241
whole_mean  0.948329  0.063089  0.972753  0.012603    0.968067  0.013127

                LGBM                RUSB                 SVM
                mean       std      mean       std      mean       std
abalone     0.992457   0.00407  0.969676  0.011411       1.0       0.0
cancer      0.968197  0.016527  0.962424  0.024098  0.978278  0.013687
car         0.995786  0.002909  0.952734  0.009092       1.0       0.0
letter      0.999922  0.000126  0.969298  0.005996  0.997522  0.000721
wine        0.977329  0.026207  0.987831  0.019805  0.992552  0.015756
yeast       0.989899  0.004128  0.871456  0.036796       1.0       0.0
whole_mean  0.987265  0.008994  0.952237  0.017866  0.994725  0.005027

precision

                 MTS              MTSBag           SMOTEMTSBag            \
                mean       std      mean       std        mean       std
abalone     0.432887  0.066951  0.419094    0.0781     0.54633  0.108676
cancer      0.832648  0.175035  0.883341  0.031894    0.497859    0.1059
car         0.474451  0.122336  0.526322  0.090173    0.519169  0.100121
letter      0.609466  0.139608  0.890832  0.052847    0.541985  0.096867
wine        0.907857  0.110577  0.980357  0.043293    0.464095  0.127131
yeast       0.179135  0.102304  0.220962  0.161983    0.508766  0.089099
whole_mean  0.572741  0.119468  0.653485  0.076382    0.513034  0.104632

                LGBM                RUSB                 SVM
                mean       std      mean       std      mean       std
abalone     0.561227  0.131429  0.346409  0.114216       NaN       NaN
cancer       0.94036  0.032227  0.937376  0.034403  0.957785  0.026337
car         0.901116  0.064442  0.402714  0.091953       NaN       NaN
letter      0.998085  0.003084  0.552782  0.053867  0.936897  0.017096
wine        0.942525  0.065743   0.97375  0.043481  0.979167  0.045005
yeast       0.341667  0.205818   0.16399  0.079053       NaN       NaN
whole_mean   0.78083   0.08379  0.562837  0.069496   0.95795  0.029479

gmeans

                 MTS              MTSBag           SMOTEMTSBag            \
                mean       std      mean       std        mean       std
abalone      0.91832  0.041723  0.900504   0.05133    0.897864  0.013202
cancer      0.817063  0.288375   0.94993  0.013844    0.889267  0.011007
car         0.942224  0.056481  0.938391  0.053516    0.891002  0.009697
letter      0.752508  0.049111  0.816376  0.031145    0.890204  0.012123
wine        0.940422   0.04915  0.988017  0.020673    0.897203  0.009591
yeast       0.471262  0.115572  0.403542  0.289151    0.893784  0.011843
whole_mean  0.806967  0.100069  0.832793   0.07661    0.893221  0.011244

                LGBM                RUSB                 SVM
                mean       std      mean       std      mean       std
abalone     0.711919  0.125232  0.879226  0.104006       0.0       0.0
cancer      0.954068   0.02236  0.944952   0.02305  0.966419  0.019468
car         0.939128  0.058842   0.85029  0.074369       0.0       0.0
letter      0.984985  0.010271  0.953188  0.012242  0.920218  0.012599
wine        0.955983  0.045957  0.989198  0.015911  0.983573  0.027079
yeast       0.358601  0.150648  0.680362   0.09406       0.0       0.0
whole_mean  0.817447  0.068885  0.882869   0.05394  0.478368  0.009858

RS

                 MTS              MTSBag           SMOTEMTSBag            \
                mean       std      mean       std        mean       std
abalone     0.884577  0.083679  0.844592  0.098538    0.854236  0.036496
cancer           inf       NaN  1.035763  0.036123     0.84626  0.024158
car         0.977734  0.127323  0.948836  0.109179    0.845915  0.031797
letter      0.588179   0.07346  0.671874  0.050895    0.837236  0.022603
wine        0.952574  0.117717  1.004545  0.049283    0.875945  0.028223
yeast       0.252175   0.12889  0.252804  0.201269    0.851956  0.031012
whole_mean       inf  0.106214  0.793069  0.090881    0.851925  0.029048

                LGBM                RUSB                 SVM
                mean       std      mean       std      mean       std
abalone     0.529687  0.193797  0.834398  0.189872       0.0       0.0
cancer      0.971426  0.036844   0.96573   0.05997  0.976076  0.027836
car         0.892739  0.110442  0.802944  0.143092       0.0       0.0
letter      0.970443  0.020225  0.967258  0.026766  0.851163  0.023457
wine        0.960819  0.103541  1.003601  0.038863  0.983263  0.059762
yeast       0.151936  0.087501  0.620049  0.157106       0.0       0.0
whole_mean  0.746175  0.092058  0.865663  0.102612  0.468417  0.018509